// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbnkkpvikujczyhojnoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibmtrcHZpa3VqY3p5aG9qbm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDM3MzUsImV4cCI6MjA2MzA3OTczNX0.6Tf-MFdO4cgAcXSZ7GgnAA_EcpXsYjg2uO8pNLWpYhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);